### ISSUE TITLE
v1 specs

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/floating-label#1]
Inspired by this:
![](http://dribbble.s3.amazonaws.com/users/6410/screenshots/1254439/form-animation-_gif_.gif)
- $().floatingLabel()
- automatically add a label above input field when there is a value in the input field
- add label-active and label-inactive classes
- if input field has an ID, add a for="ID" on the floating label

**Comment by ghost** [comment]
tap into the valid() library so that it does something with the labels on error?

**Comment by jgallen23** [comment]
for sure.  will definitely do that for v2

**Comment by dawnerd** [comment]
Password fields could do something special as well as the password get more(or less) secure.

**Comment by dawnerd** [comment]
So all of the items in his spec are pretty much ready.

Want any events to be triggered?

**Comment by jgallen23** [comment]
Probably, but not for v1.  We need to think about if we want to integrate valid in this lib or create a new lib that uses both

**Comment by dawnerd** [comment]
If valid could trigger an event on the input then we could listen for it then do whatever we need.
